protected-worlds:
  - lobby
# Can op do whatever the fuck they want? ( in protected worlds! )
op-bypass: false
# Limit these things ?
breaking-blocks: true
placing-blocks: true
item-pickup: true
item-drop: true
join-msg: true
quit-msg: true
tp-spawn-on-join: true
spawn-pitch: 0.0
spawn-yaw: 0.0

messages:
  join: "<gradient:#00FF00:#FF0000>[+] {PLAYER}</gradient>"
  quit: "<gradient:#00FF00:#FF0000>[-] {PLAYER}</gradient>"
